# Generated by Django 3.2.4 on 2021-12-19 16:21

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0005_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='medium',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('bangla', 'bangla'), ('english', 'english'), ('math', 'math'), ('urdu', 'urdu')], default='bangla', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='tution/images'),
        ),
    ]
