# Generated by Django 3.2.4 on 2021-12-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0012_postfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfile',
            name='image',
            field=models.ImageField(upload_to='tution/images'),
        ),
    ]
