# Generated by Django 3.2.4 on 2021-12-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0013_alter_postfile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
